on:
  push:
    paths:
      - 'Architeuthis dux/**'

jobs:
  build:
    runs-on: ubuntu-latest
    name: Release
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: "Build & test"
        run: |
          cp LICENSE Architeuthis\ dux/gerbers/ &&
          cd Architeuthis\ dux/gerbers/ &&
          zip ../../Architeuthis\ dux.zip *
      - uses: "marvinpinto/action-automatic-releases@latest"
        with:
          repo_token: "${{ secrets.GITHUB_TOKEN }}"
          automatic_release_tag: "latest"
          title: "Architeuthis dux"
          files: |
            LICENSE
            Architeuthis\ dux.zip
